### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by tomwhite**
Small change to debug the build with goal of solving #8.

### CODE REVIEW

**Comment by tomwhite** [comment]
Opened https://github.com/horta/zlib.install/pull/13 to fix the Windows build

**Comment by tomwhite** [comment]
Tests are failing for almosthere: https://github.com/limix/cbgen/runs/5772158281?check_suite_focus=true

**Comment by tomwhite** [comment]
Status: tests pass on ubuntu and macos. Wheels build on macos, but not on ubuntu. Tests and wheels not working on windows.

**Comment by tomwhite** [comment]
Tests are passing everywhere now since https://github.com/horta/zlib.install/pull/13 was fixed.

The wheels build is still not working on ubuntu, see https://github.com/limix/cbgen/runs/6523063318?check_suite_focus=true. Any thought on how to fix this @horta?

**Comment by tomwhite** [comment]
@ horta why does cbgen need a progress bar library (https://github.com/horta/almosthere)? I can't see where it is used either (but I may be missing something).

**Comment by horta** [comment]
That is because bgen depends on it: https://github.com/limix/bgen/blob/961ed6e875169d2c753a5d1e5ef52104017f0030/src/metafile_write.h#L96

I'm not sure if that is necessary anymore (it depends how fast it is but I don't remember...).

**Comment by horta** [comment]
Culprit (Windows SDK): https://github.com/microsoft/vcpkg/issues/15035#issuecomment-1069125693

**Comment by horta** [comment]
Workaround ?: https://github.com/ApexAI/iceoryx/commit/dc1498574a17c462df95e42868f2d5f4cc070b65

**Comment by tomwhite** [comment]
Thanks @horta. I tried the workaround (`windows-latest`), but unfortunately it still failed: https://github.com/limix/cbgen/runs/6554207174?check_suite_focus=true. Also, ubuntu is failing too.

Not sure what to try next as I'm not very familiar with the code.

**Comment by horta** [comment]
Hey @tomwhite , could you edit ci/win-deps to have:

```
if [[ $BITS == "32" ]]
then
    export CMAKE_GENERATOR_PLATFORM=Win32
    export CMAKE_GENERATOR="Visual Studio 17 2022"
    PREFIX="/c/Program Files (x86)"
else
    export CMAKE_GENERATOR_PLATFORM=x64
    export CMAKE_GENERATOR="Visual Studio 17 2022"
    PREFIX="/c/Program Files"
fi
```

?

I think that will sort out the remainig building error...

**Comment by horta** [comment]
Almost:


```
cp: cannot stat '/c/Program Files (x86)/zlib/bin/zlib.dll': No such file or directory
```


I will be releasing a new bgen version today with all those libraries built-in so we don't see those errors anymore.

**Comment by tomwhite** [comment]
Great! Thanks @horta.

**Comment by tomwhite** [comment]
> I will be releasing a new bgen version today with all those libraries built-in so we don't see those errors anymore.

Any updates on the bgen release @horta? I couldn't see it when I checked. Thanks.

**Comment by horta** [comment]
Hi @tomwhite , could you ping my this weekend so I dont forget it? It was nearly done but I had to travel back to UK and then I forgot everything I was doing hehe

**Comment by tomwhite** [comment]
@horta ping (as requested)!

**Comment by horta** [comment]
Hey @tomwhite , could you take a look at the main repo? It is building for manylinux2014 and macos but I had to disable Windows for now (have a look at the commit message, please).

It was a nightmare to refactor to building process to a much simpler (still complex) one, but I'm depending on the Python poetry 1.2.x beta releases, and I'm waiting for the new beta release to try Windows again.

(If you have an idea on how to build for windows, please, let me know). I feel that we are close to a simple building workflow for it.

**Comment by tomwhite** [comment]
@horta this is working for me on Linux - thanks for fixing it.

I don't have an experience or suggestions for the Windows builds I'm afraid. But it looks like a new poetry 1.2.x beta release is out now.

**Comment by horta** [comment]
Gonna give a go with Poetry [1.2.0b3](https://github.com/python-poetry/poetry/releases/tag/1.2.0b3)

**Comment by horta** [comment]
Trying it here: https://github.com/limix/cbgen/tree/try-win

**Comment by CarlKCarlK** [comment]
Thanks for giving it a try. Let me know if there is anything you'd like me to test.

Are other folks having problems with Poetry and Windows? (I assume so)

**Comment by horta** [comment]
Hi @CarlKCarlK =)

Could you give it a try?

Theoretically, you need:

- Python 3.8 or above installed
- pipx (python -m pip install --user pipx) or ((python3 -m pip install --user pipx)
- pipx install poetry==1.2.0b3

From the project folder, you can then type: `poetry install`

That is the step in which the building process takes forever. The first step of this process is actually installing `cmake` and `cffi` python packages, which should not take long as pypi has wheels for them...

**Comment by CarlKCarlK** [comment]
I was out most of the day but will be able to work on this tomorrow afternoon
________________________________

**Comment by CarlKCarlK** [comment]
Danilo,

When you do bgen-reader, please include the recent https://github.com/limix/bgen-reader-py/pull/44.
It helps users use read-only UK Biobank files.


  *   Carl

**Comment by CarlKCarlK** [comment]
Danilo,

I've put what happens below.

For some reason it pops up a CMake GUI a couple of times. Then it fails.

I don't know what version of cmake it is trying to call.


  *   Carl

p.s.


***@***.***

(mini38d) d:\OneDrive\programs\cbgen>poetry install
Updating dependencies
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/e9/06/d3d367b7af6305b16f0d28ae2aaeb86154faResolving dependencies... Downloading https://files.pythonhosted.org/packages/13/b1/0c22aa7ca1deda4915cdec9562f839546bb2Resolving dependencies... Downloading https://files.pythonhosted.org/packages/13/b1/0c22aa7ca1deda4915cdec9562f839546bb2Resolving dependencies... Downloading https://files.pythonhosted.org/packages/13/b1/0c22aa7ca1deda4915cdec9562f839546bb2Resolving dependencies... Downloading https://files.pythonhosted.org/packages/13/b1/0c22aa7ca1deda4915cdec9562f839546bb2Resolving dependencies... Downloading https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f3Resolving dependencies... Downloading https://files.pythonhosted.org/packages/77/8b/7550e87b2d308a1b711725dfaddc19c695f8Resolving dependencies... (58.4s)

Writing lock file

Package operations: 11 installs, 3 updates, 0 removals

  * Updating certifi (2022.6.15 C:/Windows/TEMP/abs_e9b7158a-aa56-4a5b-87b6-c00d295b01fanefpc8_o/croots/recipe/certifi_1655968940823/work/certifi -> 2022.6.15)
  * Updating setuptools (61.2.0 -> 63.2.0)
  * Updating click (8.1.3 C:\Users\Carl\AppData\Roaming\Python\Python38\site-packages -> 8.1.3)
  * Installing mypy-extensions (0.4.3)
  * Installing nodeenv (1.7.0)
  * Installing pathspec (0.9.0)
  * Installing pep517 (0.12.0)
  * Installing platformdirs (2.5.2)
  * Installing typing-extensions (4.3.0)
  * Installing black (22.6.0)
  * Installing build (0.8.0)
  * Installing isort (5.10.1)
  * Installing pyright (1.1.262)
  * Installing toml (0.9.6)

Preparing build environment with build-system requirements poetry_core>=1.0.8, cffi>=1.15.1, cmake>=3.22.5
Traceback (most recent call last):
  File "d:\OneDrive\programs\cbgen\build_ext.py", line 90, in <module>
    libs += build_deps(pwd, "limix", "bgen", "4.1.9")
  File "d:\OneDrive\programs\cbgen\build_ext.py", line 74, in build_deps
    for line in open(build_dir / "CMakeCache.txt", "r"):
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\OneDrive\\programs\\cbgen\\.ext_deps\\bgen-4.1.9\\build\\CMakeCache.txt'
Installing the current project: cbgen (1.0.2)

(mini38d) d:\OneDrive\programs\cbgen>

**Pull request closed without merging**
